spring.application.name=Asset-Aware-Security-Intelligence

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://ep-fragrant-cake-anto5h2a-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_T7wpGmEiYZr9}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# ===============================
# MAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}

spring.mail.username=${MAIL_USERNAME:m.ali.zafar2005@gmail.com}
spring.mail.password=${MAIL_PASSWORD:agnl dhwg ffkz uwoq}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS_REQUIRED:true}

# Optional timeouts
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_TIMEOUT:5000}

# ===============================
# APP SETTINGS
# ===============================
aasi.app.frontend-url=${FRONTEND_URL:http://localhost:5173}
aasi.app.jwt-secret=${JWT_SECRET:611111111111fstwfsfwqsgssdvxvgashsgfdgafdauwqywte}

# ===============================
# GOOGLE OAUTH2 LOGIN
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:22500431871-8ea1k6bnhsvd9kc3c0pmnlnapffc9m4o.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=profile,email